[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [{name = "Xu Chaoqian", email = "chaoranxu@gmail.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "fastapi[all] == 0.98.0",
  "gunicorn[setproctitle] == 20.1.0",
  "tomli == 2.0.1",
  "portpicker == 1.5.2",
  "async-lru == 2.0.2",
  "maxwell-protocol @ git+https://github.com/maxwell-dev/maxwell-protocol-python.git@dev",
]
description = "The maxwell server implementation for python."
license = {file = "LICENSE"}
name = "maxwell-server"
readme = "README.md"
requires-python = ">=3.7"
version = "0.5.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "[%(levelname)8s] %(asctime)s (%(filename)s:%(lineno)s) %(message)s"
log_cli_level = "DEBUG"

[project.optional-dependencies]
test = ["pytest >= 7.2.0", "pytest-asyncio >= 0.20.3", "pytest-cov[all]"]

[project.urls]
changelog = "https://github.com/maxwell-dev/maxwell-server-python/CHANGELOG.md"
repository = "https://github.com/maxwell-dev/maxwell-server-python"

[tool.hatch.metadata]
allow-direct-references = true

[tool.setuptools.packages.find]
where = [
  "maxwell",
] # list of folders that contain the packages (["."] by default)
