[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dependencies = [
    "fastapi[all] == 0.89.1",
    "gunicorn[setproctitle] == 20.1.0",
    "tomli == 2.0.1",
    "portpicker == 1.5.2",
    "maxwell-protocol @ git+https://github.com/maxwell-dev/maxwell-protocol-python.git@dev",
]
name = "maxwell-server"
version = "0.1.0"
authors = [{ name = "Xu Chaoqian", email = "chaoranxu@gmail.com" }]
description = "The maxwell server implementation for python."
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"

[project.optional-dependencies]
test = ["pytest >= 7.2.0", "pytest-cov[all]"]

[project.urls]
repository = "https://github.com/maxwell-dev/maxwell-server-python"
changelog = "https://github.com/maxwell-dev/maxwell-server-python/CHANGELOG.md"

[tool.hatch.metadata]
allow-direct-references = true
